<app-menu></app-menu>
<nav class="navbar navbar-inverse bg-dark navbar-dark">
  <ul class="navbar-nav">
    <!--<li><a href="javascript:void(0)">Hi {{name}}</a></li>-->
    <li class="nav-item"><a class="nav-link" [routerLink]="['/training/Angular2/Angular2']">HOME</a></li>
    <li class="nav-item"><a class="nav-link" [routerLink]="['/admin']">Admin</a></li>
    <li class="nav-item"><a class="nav-link" [routerLink]="['/training/Angular2/Angular2/Intro']">Modules</a></li>
    <li class="nav-item"><a class="nav-link" [routerLink]="['/training/this.videodata1[0].name']" (click)=Quiz(this.videodata1[0].name)>Quizzes</a></li>
    <li class="nav-item"><a class="nav-link" [routerLink]="['/training/Angular2/Angular2/video']">Videos</a></li>
    <li class="nav-item"><a class="nav-link"[routerLink]="['/training/Angular2/Angular2/files']">Files</a></li>
    <li class="nav-item"><a class="nav-link"[routerLink]="['/login']" (click)=logout()>LogOut</a></li>
  </ul>
</nav>
<h1>Error Handling</h1>
<p>Angular 2 applications have the option of error handling. This is done by including the ReactJS catch library and then using the catch function.

<p>Let’s see the code required for error handling. This code can be added on top of the chapter for CRUD operations using http.

<p>In the product.service.ts file, enter the following code −</p>

<!--<pre>
  <code>
    import { Injectable } from '@angular/core'; 
    import { Http , Response } from '@angular/http'; 
    import { Observable } from 'rxjs/Observable'; 
    
    import 'rxjs/add/operator/map'; 
    import 'rxjs/add/operator/do'; 
    import 'rxjs/add/operator/catch'; 
    import { IProduct } from './product';  
    
    @Injectable() 
    export class ProductService { 
       private _producturl = 'app/products.json'; 
       constructor(private _http: Http){}  
    
       getproducts(): Observable<IProduct[]> { 
          return this._http.get(this._producturl) 
          .map((response: Response) => <IProduct[]> response.json()) 
          .do(data => console.log(JSON.stringify(data))) 
          .catch(this.handleError); 
       }  
       
       private handleError(error: Response) { 
          console.error(error); 
          return Observable.throw(error.json().error()); 
       } 
    }
  </code>
</pre>-->

<ul>
<li>The catch function contains a link to the Error Handler function.</li>

<li>In the error handler function, we send the error to the console. We also throw the error back to the main program so that the execution can continue.</li>
</ul>

<p>Now, whenever you get an error it will be redirected to the error console of the browser.</p>

<ul class="pagination">
    <li class="page-item"><a class="page-link" href="/training/Angular2/Angular2/Intro/directive">Previous</a></li>
    <li class="page-item"><a class="page-link" href="/training/Angular2/Angular2/Intro/routing">Next</a></li>
  </ul>